import { createHash } from "node:crypto";
import {
  existsSync,
  mkdirSync,
  readFileSync,
  rmSync,
  writeFileSync,
} from "node:fs";
import { dirname, isAbsolute, join, normalize, resolve, sep } from "node:path";

/**
 * Uploaded files live outside the database. The same root the backup tools use
 * (scripts/backup/paths.mjs) — a snapshot only pairs with its files when both
 * halves agree on where those files are.
 */
export const DEFAULT_UPLOADS_DIRECTORY = "./var/uploads";

export class UploadStorageError extends Error {
  constructor(message: string) {
    super(message);
    this.name = "UploadStorageError";
  }
}

export function uploadsRoot(
  env: Record<string, string | undefined> = process.env,
  appRoot = process.cwd(),
): string {
  return resolve(
    appRoot,
    env.UPLOADS_ROOT?.trim() || DEFAULT_UPLOADS_DIRECTORY,
  );
}

/**
 * A storage key is always relative to the root and always stays inside it. A key
 * is generated by this codebase, never supplied by a browser, but the check is
 * here anyway: this is the one place a path becomes a filesystem read.
 */
export function resolveStoredPath(root: string, storageKey: string): string {
  if (typeof storageKey !== "string" || storageKey.trim().length === 0) {
    throw new UploadStorageError("A stored file needs a storage key.");
  }
  if (isAbsolute(storageKey)) {
    throw new UploadStorageError("A storage key must be relative.");
  }
  const normalized = normalize(storageKey);
  if (normalized === ".." || normalized.startsWith(`..${sep}`)) {
    throw new UploadStorageError("A storage key must stay inside uploads.");
  }
  const path = join(root, normalized);
  const rootWithSep = root.endsWith(sep) ? root : `${root}${sep}`;
  if (!path.startsWith(rootWithSep)) {
    throw new UploadStorageError("A storage key must stay inside uploads.");
  }
  return path;
}

export function writeStoredFile(
  root: string,
  storageKey: string,
  bytes: Uint8Array,
): { sha256: string; byteSize: number } {
  const path = resolveStoredPath(root, storageKey);
  mkdirSync(dirname(path), { recursive: true });
  const buffer = Buffer.from(bytes);
  writeFileSync(path, buffer, { mode: 0o600 });

  // Hash what is on disk, not what was handed to us: the manifest is a claim
  // about the file, and a claim about a buffer proves nothing after a restore.
  const written = readFileSync(path);
  return {
    sha256: createHash("sha256").update(written).digest("hex"),
    byteSize: written.byteLength,
  };
}

export function readStoredFile(root: string, storageKey: string): Buffer {
  const path = resolveStoredPath(root, storageKey);
  if (!existsSync(path)) {
    throw new UploadStorageError("That file is no longer on disk.");
  }
  return readFileSync(path);
}

export function storedFileExists(root: string, storageKey: string): boolean {
  try {
    return existsSync(resolveStoredPath(root, storageKey));
  } catch {
    return false;
  }
}

export function deleteStoredFile(root: string, storageKey: string): void {
  rmSync(resolveStoredPath(root, storageKey), { force: true });
}
